#
# Copyright (c) 2017-2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

dist: trusty

language: go

go:
  - 1.8
  - stable

env:
  - target_branch=$TRAVIS_BRANCH

before_script:
  - ".ci/static-checks.sh github.com/kata-containers/tests"
