#
# Copyright (c) 2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: constraints-cpu-test
  annotations:
    io.kubernetes.cri-o.TrustedSandbox: "false"
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - name: first-cpu-container
    image: busybox
    command:
        - sleep
        - "30"
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "500m"
