[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/go-logfmt/logfmt"
  version = "0.3.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[prune]
  go-tests = true
  unused-packages = true
